INSERT OR IGNORE INTO stellen (
    kennziffer,
    titel,
    arbeitsort,
    eintrittsdatum,
    karrierestufe,
    beschaeftigungsgrad,
    befristung,
    verguetung,
    wer_wir_sind,
    das_erwartet_dich,
    aufgaben,
    anforderungen,
    leistungen,
    ansprechperson_name,
    ansprechperson_email,
    status
) VALUES
(
    'FIT-001',
    'Fitnesstrainer (m/w/d)',
    'Dortmund',
    '2026-11-01',
    'Berufseinstieg',
    'Vollzeit',
    'Unbefristet',
    'Nach Vereinbarung',
    'Wir sind ein wachsendes Fitnessunternehmen mit mehreren Standorten im Ruhrgebiet.',
    'Ein abwechslungsreicher Arbeitsalltag mit direktem Kontakt zu unseren Mitgliedern.',
    'Trainingsbetreuung, Erstellung individueller Trainingspläne und Durchführung von Einweisungen.',
    'Abgeschlossene Ausbildung oder Studium im Sportbereich sowie Freude am Umgang mit Menschen.',
    'Strukturierte Einarbeitung, Weiterbildungen und kostenfreie Nutzung unserer Studios.',
    'Nina Hartmann',
    'karriere@fiktivfit.example',
    'aktiv'
),
(
    'KURS-001',
    'Mitarbeiter Kursbetreuung (m/w/d)',
    'Bochum',
    '2026-12-01',
    'Berufserfahren',
    'Teilzeit',
    'Unbefristet',
    'Nach Vereinbarung',
    'Wir verbinden professionelles Training mit einer persönlichen Betreuung.',
    'Du entwickelst gemeinsam mit dem Team ein vielseitiges Kursangebot.',
    'Planung, Organisation und Durchführung von Gruppenfitnesskursen.',
    'Gültige Trainerlizenz, Zuverlässigkeit und ein motivierendes Auftreten.',
    'Flexible Einsatzzeiten, Fortbildungsbudget und kostenfreie Studionutzung.',
    'Nina Hartmann',
    'karriere@fiktivfit.example',
    'aktiv'
),
(
    'REIN-001',
    'Reinigungskraft (m/w/d)',
    'Essen',
    NULL,
    'Berufseinstieg',
    'Teilzeit',
    'Unbefristet',
    'Nach Vereinbarung',
    'Sauberkeit und ein gepflegtes Umfeld sind ein wichtiger Teil unseres Studioerlebnisses.',
    'Dich erwartet ein verlässliches Team und ein klar strukturierter Aufgabenbereich.',
    'Reinigung der Trainingsflächen, Umkleiden und Gemeinschaftsbereiche.',
    'Sorgfältige Arbeitsweise, Zuverlässigkeit und zeitliche Flexibilität.',
    'Planbare Arbeitszeiten, strukturierte Einarbeitung und Mitarbeitervorteile.',
    'Nina Hartmann',
    'karriere@fiktivfit.example',
    'aktiv'
);

